### ISSUE TITLE
Doesn't seem to work properly

### ISSUE THREAD

**Issue by KotTheKitty** [PabloMK7/CTGP7ProximityChatClient#4]
I can successfully connect my 3ds to the client, but despite other people having voice chat as well, it doesn't seem to pick up anyone. There's also a blank dropdown menu. I am using Arch Linux. You can see my experience [in the stream I did yesterday.](https://www.youtube.com/live/LXtW_814WFg)

**Comment by Str4ky** [comment]
The blank dropdown menu is supposed to show all of your available mic connected to ur PC

**Comment by KotTheKitty** [comment]
> The blank dropdown menu is supposed to show all of your available mic connected to ur PC

Yeah that's what I was thinking, but it's not working it seems

**Comment by nixRidge** [comment]
Hi there @Furdox
I am also using Arch Linux. With wine-staging 9.20, the application works but unfocusing the window and then switching back to it makes the UI entirely unresponsive.

After some experimenting, I made a Wine prefix using [Wine-GE 8.26](https://github.com/GloriousEggroll/wine-ge-custom/releases) and installed DXVK in that prefix.
This environment works perfectly.

For whoever wants to replicate this setup but isn't sure how, here's roughly what you do:
Install winetricks if you haven't, and download [Wine-GE 8.26](https://github.com/GloriousEggroll/wine-ge-custom/releases).
If you have Lutris, you probably have it in `~/.local/share/lutris/runners/wine/wine-ge-8-26-x86_64/bin/wine`

Now execute the following commands.
Replace the paths with your own depending on where you want this Wine prefix to be:
```bash
WINEARCH=win64 WINEPREFIX=/path/to/where/you/want/ctgp7voice/prefix WINE=/path/to/wine-ge-8-26-x86_64/bin/wine winetricks dxvk
```

Then you can extract the Windows version of CTGP-7 Proximity Chat in that prefix, or just anywhere you like.
Just make sure you launch it **specifically** using Wine-GE 8.26.
To make this easier, you can for example: make a .desktop file for it, make a shell script, use KDE's Menu Editor, or whatever suits your specific environment, these are just examples..

To launch directly with your terminal:
```bash
cd /path/to/directory/containing/exe/
```
```bash
WINEPREFIX=/path/to/where/you/put/ctgp7voice/prefix /path/to/wine-ge-8-26-x86_64/bin/wine 'CTGP-7 Proximity Chat Client.exe'
```
Here is another example, showing how I set up a shortcut in KDE Menu Editor. Please notice the quotes, they are important because the executable has spaces in its name:
![bilde](https://github.com/user-attachments/assets/dba0f403-d4bf-4f3e-8db3-87f0cf6c8ec3)

**Comment by KotTheKitty** [comment]
yeah the windows build was working perfectly fine for me under proton ge, it's just the Linux build that was broken

I did it using steam's add a non-steam game functionality, but a shortcut like that also works

**Comment by KotTheKitty** [comment]
will be closing as there no longer is a Linux build for the latest version
